package ingest

import (
	"path/filepath"

	"github.com/tesserix/kora/api/internal/nutrition"
)

// AliasFile is the curated global alias file, resolved against the same
// directory as the sources below. Not a Source: aliases are applied after the
// load (so an alias can name a row the same run created) and go through
// UpsertGlobalAliases rather than the food-item loader.
//
// Small and hand-audited on purpose — a global alias resolves at score 1.0,
// which is the auto-log tier, so a wrong entry logs the wrong food
// confidently. Bulk-importing transliterations is NOT safe: IFCT is raw
// commodities while people type cooked dishes, so `moong dal` → `Green gram,
// dal` is 325 kcal/100g against ~120 cooked.
const AliasFile = "aliases.json"

// Source is one food data file and the provenance every row it carries is
// stamped with.
type Source struct {
	File       string
	Provenance string
}

// sources is the single place a food data file is declared.
//
// It used to be nine `-flag path` pairs on cmd/ingest, which the kora-api seed
// Job's command in tesserix-k8s had to repeat in full. A source added here
// without a matching line over there made the Job exit 1 and crash-loop prod —
// which happened THREE times in one day (kora#215's -ifct, then -ausnut, then
// -aliases). Adding a source is now a line in this table plus the file itself;
// the chart passes one directory and never needs to know.
//
// TestSourceFilesExist asserts every file below is present in api/data/food,
// so the remaining way to get this wrong — naming a file that was never
// committed — fails CI here instead of the seed Job in prod.
//
// Run processes files in sorted path order and the alphabetically-first file
// wins any name+brand overlap, so renaming an entry changes which source wins
// a collision. Renaming is a behaviour change, not a cosmetic one.
var sources = []Source{
	// AFCD staples: the colloquial-naming Australian set ("White rice,
	// cooked"), and the only AFCD file carrying serving sizes.
	{"afcd_staples.json", nutrition.ProvenanceAFCD},
	// The full FSANZ release (1,578 foods), from scripts/afcd_convert.py.
	// Kept separate from staples rather than replacing it: the two do not
	// overlap by name — Release 3 uses formal naming ("Rice, white, cooked") —
	// and it is per-100 g reference data with no serving stated. See kora#184.
	{"afcd_release3.json", nutrition.ProvenanceAFCD},
	// IFCT 2017, from scripts/ifct_convert.py against
	// github.com/ifct2017/compositions at tag 2.0.5 — the MIT-licensed tag;
	// HEAD is AGPL-3.0. The Indian counterpart to afcd_release3: per-100 g
	// reference data, no serving sizes, no brands. Indian staples previously
	// had no Indian-measured row to resolve to at all. See kora#212.
	{"ifct.json", nutrition.ProvenanceIFCT},
	// AUSNUT 2023, from scripts/ausnut_convert.py. FSANZ's survey database of
	// foods AS CONSUMED — the Australian counterpart to the takeaway coverage
	// USDA gives the US. AFCD alone left the index with eight outlet-style
	// Australian rows. Generic only; AUSNUT never names a brand.
	{"ausnut.json", nutrition.ProvenanceAUSNUT},
	// Australian branded products from OpenFoodFacts, filtered by
	// scripts/off_convert.py to those that can actually answer a nutrition
	// question (5,666 of ~73,300 AU entries). Every row carries a barcode, so
	// this also feeds the scan path.
	//
	// ODbL: this data obliges Kora to ATTRIBUTE OpenFoodFacts in the app.
	{"off_au.json", nutrition.ProvenanceOFF},
	// The New Zealand and Indian slices of the same OFF export, produced in
	// the same off_convert.py pass as off_au. Rows carry an explicit per-row
	// locale, so a single OFF provenance stays correct across regions. A
	// trans-Tasman product present in several slices resolves from the
	// alphabetically-first file (off_au), per Run's collision rule — the
	// nutrition is identical, only the locale boost differs.
	{"off_in.json", nutrition.ProvenanceOFF},
	{"off_nz.json", nutrition.ProvenanceOFF},
	{"usda_common.json", nutrition.ProvenanceUSDA},
	// FNDDS survey foods, from scripts/fndds_convert.py — USDA's foods AS
	// CONSUMED with measured portions, the US counterpart of ausnut.json.
	// Sorts before usda_sr_legacy.json so a name collision resolves to the
	// current release rather than to data frozen in 2018.
	{"usda_fndds.json", nutrition.ProvenanceUSDA},
	// Generated by cmd/srconvert.
	{"usda_sr_legacy.json", nutrition.ProvenanceUSDA},
	{"au_in_dishes.json", nutrition.ProvenanceCurated},
}

// Sources resolves the source table against dir, returning the path→provenance
// map Run takes.
func Sources(dir string) map[string]string {
	files := make(map[string]string, len(sources))
	for _, s := range sources {
		files[filepath.Join(dir, s.File)] = s.Provenance
	}
	return files
}

// SourceFiles returns the declared filenames, unresolved. For tests and for
// anything that needs to know what the image must ship.
func SourceFiles() []string {
	files := make([]string, 0, len(sources)+1)
	for _, s := range sources {
		files = append(files, s.File)
	}
	return append(files, AliasFile)
}
