// GENERATED by design-system/scripts/export-rn-tokens.mjs — do not edit by hand.
export const lightColors = {
  "background": "#ffffff",
  "foreground": "#0f1729",
  "card": "#ffffff",
  "cardForeground": "#0f1729",
  "primary": "#6b55df",
  "primaryForeground": "#ffffff",
  "secondary": "#f4f4ff",
  "secondaryForeground": "#322c61",
  "muted": "#f5f5ff",
  "mutedForeground": "#666682",
  "accent": "#f4f4ff",
  "accentForeground": "#6b55df",
  "destructive": "#dd2725",
  "destructiveForeground": "#ffffff",
  "border": "#e3e4f4",
  "input": "#e3e4f4",
  "ring": "#6b55df",
  "success": "#25a351",
  "warning": "#e59d23",
  "error": "#dd2725",
  "info": "#1a89c5"
} as const;
export const darkColors = {
  "background": "#10101e",
  "foreground": "#f4f4ff",
  "card": "#19182a",
  "cardForeground": "#f4f4ff",
  "primary": "#9c92ff",
  "primaryForeground": "#10101e",
  "secondary": "#292743",
  "secondaryForeground": "#f4f4ff",
  "muted": "#292743",
  "mutedForeground": "#ababc7",
  "accent": "#373267",
  "accentForeground": "#f4f4ff",
  "destructive": "#dc6b66",
  "destructiveForeground": "#10101e",
  "border": "#302e50",
  "input": "#302e50",
  "ring": "#9c92ff",
  "success": "#35c26d",
  "warning": "#fab72a",
  "error": "#dc6b66",
  "info": "#44a8e7"
} as const;
export const spacing = {
  "xs": 4,
  "sm": 8,
  "md": 16,
  "lg": 24,
  "xl": 32,
  "2xl": 48,
  "3xl": 64
} as const;
export const radius = {
  "sm": 6,
  "md": 8,
  "lg": 10,
  "xl": 16,
  "2xl": 24,
  "3xl": 32,
  "full": 9999
} as const;
export const fontSize = {
  "xs": 12,
  "sm": 14,
  "base": 16,
  "lg": 18,
  "xl": 20,
  "2xl": 24,
  "3xl": 30,
  "4xl": 36,
  "5xl": 48
} as const;
