package main

import (
	"context"
	"flag"
	"log"
	"os"

	"github.com/tesserix/kora/api/internal/database"
	"github.com/tesserix/kora/api/internal/nutrition"
	"github.com/tesserix/kora/api/internal/nutrition/ingest"
)

func main() {
	afcd := flag.String("afcd", "data/food/afcd_staples.json", "AFCD staples JSON path")
	// The full FSANZ release (1,578 foods), generated by scripts/afcd_convert.py.
	// Separate from the staples file rather than replacing it: the two do not
	// overlap by name (Release 3 uses formal naming, "Rice, white, cooked",
	// where staples uses colloquial, "White rice, cooked"), and only staples
	// carries serving sizes — AFCD itself is per-100 g reference data with no
	// serving stated. See kora#184 for why this was needed.
	afcdFull := flag.String("afcd-full", "data/food/afcd_release3.json", "AFCD Release 3 JSON path")
	// Australian branded products from OpenFoodFacts, filtered to those that can
	// actually answer a nutrition question — see scripts/off_convert.py, which
	// keeps 5,666 of ~73,300 AU entries. Every row carries a barcode, so this
	// also feeds the scan path.
	//
	// ODbL: this data obliges Kora to ATTRIBUTE OpenFoodFacts in the app.
	offAU := flag.String("off-au", "data/food/off_au.json", "OpenFoodFacts AU products JSON path")
	usda := flag.String("usda", "data/food/usda_common.json", "USDA common foods JSON path")
	sr := flag.String("sr", "data/food/usda_sr_legacy.json", "USDA SR Legacy JSON path (generated by cmd/srconvert)")
	curated := flag.String("curated", "data/food/au_in_dishes.json", "curated AU/Indian dishes JSON path")
	backfill := flag.Bool("backfill-normalized", false, "recompute normalized_name for all rows")
	flag.Parse()

	url := os.Getenv("DATABASE_URL")
	if url == "" {
		log.Fatal("ingest: DATABASE_URL required")
	}
	db, err := database.Connect(url)
	if err != nil {
		log.Fatal(err)
	}
	repo := nutrition.NewRepository(db)
	ctx := context.Background()

	n, err := ingest.Run(ctx, repo, map[string]string{
		*afcd:     nutrition.ProvenanceAFCD,
		*afcdFull: nutrition.ProvenanceAFCD,
		*offAU:    nutrition.ProvenanceOFF,
		*usda:     nutrition.ProvenanceUSDA,
		*sr:       nutrition.ProvenanceUSDA,
		*curated:  nutrition.ProvenanceCurated,
	})
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("ingest: inserted %d food items", n)

	if *backfill {
		u, err := repo.BackfillNormalizedNames(ctx)
		if err != nil {
			log.Fatal(err)
		}
		log.Printf("ingest: backfilled %d normalized names", u)
	}
}
