package main

import (
	"context"
	"flag"
	"log"
	"os"

	"github.com/tesserix/kora/api/internal/database"
	"github.com/tesserix/kora/api/internal/nutrition"
	"github.com/tesserix/kora/api/internal/nutrition/ingest"
)

func main() {
	afcd := flag.String("afcd", "data/food/afcd_staples.json", "AFCD staples JSON path")
	// The full FSANZ release (1,578 foods), generated by scripts/afcd_convert.py.
	// Separate from the staples file rather than replacing it: the two do not
	// overlap by name (Release 3 uses formal naming, "Rice, white, cooked",
	// where staples uses colloquial, "White rice, cooked"), and only staples
	// carries serving sizes — AFCD itself is per-100 g reference data with no
	// serving stated. See kora#184 for why this was needed.
	afcdFull := flag.String("afcd-full", "data/food/afcd_release3.json", "AFCD Release 3 JSON path")
	// Australian branded products from OpenFoodFacts, filtered to those that can
	// actually answer a nutrition question — see scripts/off_convert.py, which
	// keeps 5,666 of ~73,300 AU entries. Every row carries a barcode, so this
	// also feeds the scan path.
	//
	// ODbL: this data obliges Kora to ATTRIBUTE OpenFoodFacts in the app.
	offAU := flag.String("off-au", "data/food/off_au.json", "OpenFoodFacts AU products JSON path")
	// IFCT 2017 (525 rows), generated by scripts/ifct_convert.py from
	// github.com/ifct2017/compositions at tag 2.0.5 — the MIT-licensed tag; HEAD
	// is AGPL-3.0. The Indian counterpart to afcd_release3: per-100 g reference
	// data with no serving sizes and no brands. Indian staples previously had no
	// Indian-measured row to resolve to at all. See kora#212.
	ifct := flag.String("ifct", "data/food/ifct.json", "IFCT 2017 JSON path")
	usda := flag.String("usda", "data/food/usda_common.json", "USDA common foods JSON path")
	sr := flag.String("sr", "data/food/usda_sr_legacy.json", "USDA SR Legacy JSON path (generated by cmd/srconvert)")
	curated := flag.String("curated", "data/food/au_in_dishes.json", "curated AU/Indian dishes JSON path")
	backfill := flag.Bool("backfill-normalized", false, "recompute normalized_name for all rows")
	// MUST be run once against any index ingested before kora#212's USDA brand
	// extraction landed. The loader now emits ("FILET-O-FISH", "McDONALD'S")
	// where the stored row is ("McDONALD'S, FILET-O-FISH", ""), and ingest
	// matches on name+brand — so without this the next run inserts 310
	// duplicates instead of recognising them. Idempotent; a second run is a
	// no-op.
	backfillBrands := flag.Bool("backfill-usda-brands", false,
		"move brands USDA embedded in the name into the brand column, and retype those rows")
	flag.Parse()

	url := os.Getenv("DATABASE_URL")
	if url == "" {
		log.Fatal("ingest: DATABASE_URL required")
	}
	db, err := database.Connect(url)
	if err != nil {
		log.Fatal(err)
	}
	repo := nutrition.NewRepository(db)
	ctx := context.Background()

	// Runs BEFORE Run so the stored rows already match what the loader now
	// emits; the other order would insert the duplicates this exists to avoid.
	if *backfillBrands {
		u, err := repo.BackfillUSDAEmbeddedBrands(ctx)
		if err != nil {
			log.Fatal(err)
		}
		log.Printf("ingest: moved %d embedded USDA brands into the brand column", u)
	}

	n, err := ingest.Run(ctx, repo, map[string]string{
		*afcd:     nutrition.ProvenanceAFCD,
		*afcdFull: nutrition.ProvenanceAFCD,
		*ifct:     nutrition.ProvenanceIFCT,
		*offAU:    nutrition.ProvenanceOFF,
		*usda:     nutrition.ProvenanceUSDA,
		*sr:       nutrition.ProvenanceUSDA,
		*curated:  nutrition.ProvenanceCurated,
	})
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("ingest: inserted %d food items", n)

	if *backfill {
		u, err := repo.BackfillNormalizedNames(ctx)
		if err != nil {
			log.Fatal(err)
		}
		log.Printf("ingest: backfilled %d normalized names", u)
	}
}
